### ISSUE TITLE
Resize if screensize isn't big enough

### ISSUE THREAD

**Issue by Sarkie** [NielsMasdorp/Speculum-Android#12]
![image](https://cloud.githubusercontent.com/assets/283203/12715145/7f55bb1c-c8d0-11e5-8fe6-3476f6fc31a7.png)

Can't see the time or most of the weather.

Used a phone as an example but the same on my Nvidia K1

**Comment by NielsMasdorp** [comment]
As of now the application is designed for the 2012 Nexus 7 only. I might add support in the future for multiple devices but this is not supported at this moment. The idea is that you check out the project, change the layout to suit your device and run.
