### ISSUE TITLE
I'm new on android studio, and trying by my selfie run your app on it

### ISSUE THREAD

**Issue by pulgagr** [NielsMasdorp/Speculum-Android#16]
I have just downloaded your app via android studio, and when I run it, I got this 2 errors.

Error:FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> When running gradle with java 5, 6 or 7, you must set the path to jdk8, either with property retrolambda.jdk or environment variable JAVA8_HOME

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem was found with the configuration of task ':app:compileRetrolambdaDebug'.
> Directory '/Users/tiagomassignan/Downloads/Speculum-Android/app/build/retrolambda/debug' specified for property 'inputDir' does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
==============================================================================

Could you help me out? I really want to make a mirror myself.

**Comment by NielsMasdorp** [comment]
Are you on Java 8? Retrolambda needs JDK8 to compile the source.

**Comment by pulgagr** [comment]
Yes, I got this installed 
Jdk-8u73-windows-x64.exe

Do I need something else?

**Comment by NielsMasdorp** [comment]
Do you mean you installed Java 8 or you already had it? You should have the JDK8 selected in Project Structure in Android Studio.

**Comment by pulgagr** [comment]
I already have it installed. Gonna check this project structure out if java8 is selected.

**Comment by NielsMasdorp** [comment]
Let me know, you should also run with --info or --debug to see more output. Hard to see whats failing now.

**Comment by pulgagr** [comment]
It worked!!! :D 
Should I be able to run your app in a 4.2.2 android device?

**Comment by NielsMasdorp** [comment]
Glad it worked! As of now the min Android version is 4.4. You can try and change it to 4.2.2. You will have to fix some errors then because it uses some min 4.4 functionaly.
