### ISSUE TITLE
Time and weather

### ISSUE THREAD

**Issue by heregoesnothing755** [NielsMasdorp/Speculum-Android#24]
How do I display time in AM/ PM instead of 24 hour time.  The upcoming weather does not advance each day.

**Comment by NielsMasdorp** [comment]
Hi, sorry for late response. I am looking into the 24 hour thing, it should change depending on your device system settings. About the upcoming weather, I've noticed this before, the API I use to get the forecast sometimes returns old data. Unfortunately I can only fix this by switching API's. I might do that in the future.

**Comment by JaiLaWa** [comment]
Hi guys.  To correct this problem, in the simple_layout.xml file, or the verbose_layout.xml file, for tc_time (text clock), simply change the format12hour property to h:mm

Problem solved.  I think if you put an a after it, you also get am/pm

**Comment by NielsMasdorp** [comment]
Thanks! Could you submit a pull request?
