### ISSUE TITLE
Does not display Google Calendar Event

### ISSUE THREAD

**Issue by JaiLaWa** [NielsMasdorp/Speculum-Android#27]
Sorry, folks. New at this.  Can someone elplain to me how to make Speculum see my google calendar events?  I'm having no luck finding permissions on my device to allow this.

Thanks guys.

Jaimee

**Comment by NielsMasdorp** [comment]
Hi! Are you on Marshmallow? You should get a permission dialog on startup if you are.

**Comment by JaiLaWa** [comment]
No, I think that device is on lollipop (4.4.2 sound right?). 

Regarding the pull request, I'm still so new on GitHub, I'm not sure what that means or what exactly it does  


Gwack!

**Comment by NielsMasdorp** [comment]
In that case the permission should be granted when you install the application. What makes you think the permission is missing? Are you seeing "no upcoming events" or nothing at all?

**Comment by JaiLaWa** [comment]
I'm seeing "No events today".
I keep my work roster on my calendar as well as my running schedule.  My
running schedule is set up as a series of all day events.  Will they appear?

**Comment by NielsMasdorp** [comment]
I'm actually not sure if all day events show up. Will test that asap.

**Comment by JaiLaWa** [comment]
They do not.  But the rest of the calendar seems to come up fine now. 

Gwack!

**Comment by NielsMasdorp** [comment]
Alright, i'll create a separate issue for that. Thanks!

**Comment by idezzire** [comment]
I also have the "No events today" message, neither All Day / short events shows up. I am on Jelly Bean 4.2.2, greatly appreciate your assistance!
