### ISSUE TITLE
cannot resolve symbol 'DaggerApplicationComponent'

### ISSUE THREAD

**Issue by karthikeyan-kandasamy** [NielsMasdorp/Speculum-Android#33]
I have cloned the repo and build using android studio. I got the "cannot resolve symbol DaggerApplicationComponent" Error. The DaggerApplicationComponent.java is missing.

**Comment by NielsMasdorp** [comment]
Those components are generated. After clean and rebuild project in Android Studio they should show up.

**Comment by BismeetSingh** [comment]
No they dont get recognized by android studio at all.
