### ISSUE TITLE
Fixed bug of not displaying all day calendar events

### ISSUE THREAD

**Issue by kevb2011** [NielsMasdorp/Speculum-Android#35]
Found logic in another magic mirror project (github.com/ineptech/) by Nick Hall that had code to pull back more calendar events from the past, which would include all-day calendar events.

[https://github.com/kevb2011/smart_mirror/blob/master/GoogleCalendarService.java]

**Comment by NielsMasdorp** [comment]
You can create a PR for this fix:)
