### ISSUE TITLE
Enhancement requests

### ISSUE THREAD

**Issue by kevb2011** [NielsMasdorp/Speculum-Android#36]
Hi Niels,
I love your app.  Could I suggest a couple enhancements?
1) Below the Reddit news, add daily Dilbert comic strip (http://dilbert.com) or XCD comic if easier
2) Allow option to display top post from multiple Reddit forums
3) Split calendar items into 2 scrolling lines.  First one for all day appointments and one for regular intraday appointments
4) Add option to add a couple stock prices to track and display from Yahoo finance or other

** I made a minor modification to my layout to display the weather stats, so that more items (from above) could be displayed.

Thanks in advance.

**Comment by NielsMasdorp** [comment]
I will look into 2 and 3. The other two I do not really need/like.
