### ISSUE TITLE
minor issue, there is an error if there isn't a maps key

### ISSUE THREAD

**Issue by ordago** [NielsMasdorp/Speculum-Android#39]
> Go to Google Static Maps API and register for a browser key (this is optional, only do this if you want to have the mirror show a maps view of your home on command)

On the readme you say that it's optional. I think you should specify that getting a key is optional but the resource string has to be there even if it's empty.

```
Error:(82, 25) error: cannot find symbol variable static_maps_api_key
Error:(42, 8) error: dagger.internal.codegen.ComponentProcessor was unable to process this class because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code.
```

**Comment by NielsMasdorp** [comment]
Fixed in PR #40
