### ISSUE TITLE
How to sync the calendar?

### ISSUE THREAD

**Issue by pjlosousa** [NielsMasdorp/Speculum-Android#44]
Hi
I have a tablet with no play store google. This uses aptoide store and uses calendar that is not google.
How to sync with the calendar of this own android tablet?

**Comment by NielsMasdorp** [comment]
Hi, this is not supported in Speculum. If you need this functionality you need to implement it yourself (you could always make a PR)

**Comment by pjlosousa** [comment]
Thank you for your answer
pardon my English
How do I do this?
I'm a newbie
thank you

2017-06-09 15:56 GMT+01:00 Niels Masdorp <notifications@github.com>:

**Comment by NielsMasdorp** [comment]
That is entirely dependant on the type of calendar you want to sync with. You need to find what calendar your tablet uses and see if you can find some example code.
