### ISSUE TITLE
How do i disable motion detection

### ISSUE THREAD

**Issue by mr-mangos** [NielsMasdorp/Speculum-Android#47]

**Comment by NielsMasdorp** [comment]
What do you mean? There is no built in motion detection.

**Comment by mr-mangos** [comment]
Somewhere in the README file it mentions
"This is a setup by an user who combined Speculum with a motion detector app to turn the mirror on when you enter the room."

**Comment by NielsMasdorp** [comment]
Yes, he used a separate app that is not connected to Speculum. If you are not using that app there is no motion detection.
